### PR TITLE
fix(browser-tools): update config

### PR DESCRIPTION
**Pull request by DuncanFaulkner**

### CODE REVIEW

**Comment by alexmurari** [comment]
@DuncanFaulkner look at this comment https://github.com/CircleCI-Public/browser-tools-orb/issues/90#issuecomment-1699879803

```
- browser-tools/install-browser-tools:
          chrome-version: 116.0.5845.96
          replace-existing-chrome: true <-- Add this
```

CircleCI is a little stubborn, huh?

**Comment by DuncanFaulkner** [comment]
I tried replace-existing but not with the chrome part will try that later tonight, thanks for your help on this much appreciated

**Comment by DuncanFaulkner** [comment]
Hi

As luck would have it Circle CI released orbs 1.4.5 - that now works - just can't test saucelabs I will need to look into that


Duncan Faulkner | Angular Developer

Angular Certified Developer II, MCP, MCSD, MCAD.Net, AZ-900


________________________________

**Comment by alexmurari** [comment]
Well, that's a start. 😄 

I don't know anything about SauceLabs testing; but I'll try to help and see what I can find.

**Comment by DuncanFaulkner** [comment]
Same, again thanks for your help really appreciated

**Pull request merged**
