### PR TITLE
Update Angular version and fix NgClass directive

### PR DESCRIPTION
**Pull request by skovalyov**
Fix proposal for ngx-layout/issues#49

In angular/angular#53831 `NgClass` directive constructor signature was updated, which is a breaking change for Angular Flex Layout. This change updates the signature by removing `iterableDiffers` and `keyValueDiffers`, which are not used anymore.

### CODE REVIEW

**Comment by DuncanFaulkner** [comment]
@skovalyov thanks for the PR, I was looking at this over the weekend and thought that this seemed like the obvious solution, but it just felt too easy, plus I wasn't sure if that would break anything else, though all unit tests passed.

I will merge your PR into main and into the 17 branch as soon as I can, again thanks for the PR

**Review by DuncanFaulkner — APPROVED** [review]
LGTM

**Comment by minijus** [comment]
There is release tag in GH, but v17.0.1 is missing in npm.

**Comment by DuncanFaulkner** [comment]
@minijus I had pushed the GH release but it was getting late and just didn't get to it - will try and do it now,

**Pull request merged**
